# Generated by Django 5.2 on 2025-04-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Banner title')),
                ('image', models.ImageField(upload_to='banners', verbose_name='Banner image')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Project title')),
                ('slug', models.SlugField(max_length=256, verbose_name='Project slug')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Project image')),
                ('structured_data', models.JSONField(blank=True, null=True, verbose_name='Structured Data (JSON-LD)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Banner image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(upload_to='gallery', verbose_name='Gallery image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
