# Generated by Django 5.2 on 2025-05-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='structured_data',
        ),
    ]
