# Generated by Django 5.2 on 2025-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_structured_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='card_image',
            field=models.ImageField(default=1, upload_to='projects', verbose_name='Project card image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(default=1, upload_to='gallery', verbose_name='Banner image'),
            preserve_default=False,
        ),
    ]
