# Generated by Django 5.2 on 2025-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image_project_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Project name'),
        ),
    ]
