# Generated by Django 5.2 on 2025-05-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Projects page Banner', 'verbose_name_plural': 'Projects page Banner'},
        ),
    ]
