# Generated by Django 5.2 on 2025-05-20 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_alter_seodata_options_remove_feedback_last_name_and_more'),
        ('projects', '0005_alter_mainbanner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('seodata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.seodata')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Main Banner image')),
                ('banner_description', models.TextField(verbose_name='Main Banner Description')),
                ('banner_slogan', models.CharField(max_length=256, verbose_name='Main Banner slogan')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Main Banner title')),
            ],
            options={
                'abstract': False,
            },
            bases=('others.seodata', models.Model),
        ),
        migrations.DeleteModel(
            name='MainBanner',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='card_image',
            new_name='cardImage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default=1, help_text='Residential or Commercial or etc', max_length=256, verbose_name='Project category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1, verbose_name='Project description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default=1, max_length=256, verbose_name='Project location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(default=1, max_length=158, verbose_name='Meta Description for SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(default=1, max_length=55, verbose_name='Meta Title for SEO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=1, max_length=512, verbose_name='Project name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=1, max_length=10, verbose_name='Project year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=512, verbose_name='Project slug'),
        ),
    ]
