# Generated by Django 5.2 on 2025-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectspage_delete_mainbanner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectspage',
            options={'verbose_name': 'Projects Page', 'verbose_name_plural': 'Projects Page'},
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(default=1, max_length=100, verbose_name='Project area'),
            preserve_default=False,
        ),
    ]
