
services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: gunicorn --workers 3 jdv_backend_config.wsgi:application --bind 0.0.0.0:8000
