# Generated by Django 5.2 on 2025-04-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Maintenance Title')),
                ('image', models.ImageField(upload_to='maintenance/', verbose_name='Maintenance Image')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Service Name')),
                ('page_title', models.CharField(max_length=512, verbose_name='Page Title')),
                ('main_image', models.ImageField(upload_to='services/', verbose_name='Main Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(max_length=256, verbose_name='Project slug')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Maintenance Text')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.maintenance')),
            ],
            options={
                'verbose_name': 'Maintenance Service',
                'verbose_name_plural': 'Maintenance Service',
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Banner title')),
                ('image', models.ImageField(upload_to='banners', verbose_name='Banner image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
