# Generated by Django 5.2 on 2025-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='banners', verbose_name='Banner image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default=1, max_length=256, verbose_name='Banner title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=256, verbose_name='Service slug'),
        ),
        migrations.DeleteModel(
            name='MainBanner',
        ),
    ]
