# Generated by Django 5.2 on 2025-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_service_title_alter_service_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='banners', verbose_name='Main Banner image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(upload_to='services/', verbose_name='Service Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Main Banner title'),
        ),
    ]
