# Generated by Django 5.2 on 2025-05-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_image_alter_service_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='text',
            field=models.TextField(default=1, help_text='Enter each bullet point on a new line'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.service'),
        ),
        migrations.DeleteModel(
            name='MaintenanceService',
        ),
    ]
