# Generated by Django 5.2 on 2025-05-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_maintenance_text_alter_maintenance_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenances'},
        ),
    ]
