# Generated by Django 5.2 on 2025-05-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_maintenance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(default=1, max_length=158, verbose_name='Meta Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(default=1, max_length=55, verbose_name='Meta Title'),
            preserve_default=False,
        ),
    ]
