# Generated by Django 5.2 on 2025-05-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_alter_contactpage_banner_image'),
        ('services', '0006_service_meta_description_service_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureService',
            fields=[
                ('seodata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.seodata')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Main Banner image')),
                ('banner_description', models.TextField(verbose_name='Main Banner Description')),
                ('banner_slogan', models.CharField(max_length=256, verbose_name='Main Banner slogan')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Main Banner title')),
                ('banner_title_gold', models.CharField(max_length=256, verbose_name='Main Banner title gold')),
                ('banner_subtitle', models.CharField(max_length=256, verbose_name='Main Banner subtitle')),
                ('our_approach_title', models.CharField(max_length=256, verbose_name='Our Approach Title')),
                ('our_approach_description', models.TextField(verbose_name='Our Approach Description')),
                ('our_approach_image', models.ImageField(upload_to='services/architecture/', verbose_name='Our Approach Image')),
                ('our_approach_stats', models.JSONField(default=list, help_text='{"value": "data", "label": "data"},', verbose_name='Stats')),
                ('our_approach_slogan', models.CharField(max_length=256, verbose_name='Our Approach Slogan')),
                ('featured_project_name', models.CharField(max_length=256, verbose_name='Featured Project Name')),
                ('featured_project_description', models.TextField(verbose_name='Featured Project Description')),
                ('featured_project_image_big', models.ImageField(upload_to='services/architecture/', verbose_name='Featured Project Image big')),
                ('featured_project_image_small', models.ImageField(upload_to='services/architecture/', verbose_name='Featured Project Image small')),
                ('featured_project_image_small_second', models.ImageField(upload_to='services/architecture/', verbose_name='Featured Project Image small second')),
                ('featured_project_location', models.CharField(max_length=256, verbose_name='Featured Project Location')),
                ('featured_project_area', models.CharField(max_length=256, verbose_name='Featured Project Area')),
                ('featured_project_year', models.CharField(max_length=256, verbose_name='Featured Project Year')),
                ('featured_project_type', models.CharField(max_length=256, verbose_name='Featured Project Type')),
            ],
            options={
                'abstract': False,
            },
            bases=('others.seodata', models.Model),
        ),
        migrations.CreateModel(
            name='FitOutService',
            fields=[
                ('seodata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.seodata')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Main Banner image')),
                ('banner_description', models.TextField(verbose_name='Main Banner Description')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Main Banner title')),
                ('banner_title_gold', models.CharField(max_length=256, verbose_name='Main Banner title gold')),
                ('banner_subtitle', models.CharField(max_length=256, verbose_name='Main Banner subtitle')),
                ('about_service_title', models.CharField(max_length=256, verbose_name='About Service Title')),
                ('about_service_description', models.TextField(verbose_name='About Service Description')),
                ('about_service_image', models.ImageField(upload_to='services/fit_out/', verbose_name='About Service Image')),
                ('fit_out_expertise_description', models.TextField(verbose_name='Fit Out Expertise Description')),
                ('transformation_process_description', models.TextField(verbose_name='Transformation Process Description')),
                ('specialized_services_description', models.TextField(verbose_name='Specialized Services Description')),
            ],
            options={
                'abstract': False,
            },
            bases=('others.seodata', models.Model),
        ),
        migrations.CreateModel(
            name='InteriorDesignService',
            fields=[
                ('seodata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.seodata')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Main Banner image')),
                ('banner_description', models.TextField(verbose_name='Main Banner Description')),
                ('banner_slogan', models.CharField(max_length=256, verbose_name='Main Banner slogan')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Main Banner title')),
                ('banner_title_gold', models.CharField(max_length=256, verbose_name='Main Banner title gold')),
                ('banner_subtitle', models.CharField(max_length=256, verbose_name='Main Banner subtitle')),
                ('experience_header', models.CharField(max_length=256, verbose_name='Experience Header')),
                ('experience_title', models.CharField(max_length=256, verbose_name='Experience Title')),
                ('experience_description', models.TextField(verbose_name='Experience Description')),
                ('experience_image', models.ImageField(upload_to='services/interior_design/', verbose_name='Experience Image')),
                ('experience_stats', models.JSONField(default=list, help_text='{"value": "data", "label": "data"},', verbose_name='Stats')),
                ('experience_slogan', models.CharField(max_length=256, verbose_name='Experience Slogan')),
                ('our_expertise_title', models.CharField(max_length=256, verbose_name='Our Expertise Title')),
                ('our_expertise_description', models.TextField(verbose_name='Our Expertise Description')),
                ('our_methodology_title', models.CharField(max_length=256, verbose_name='Our Methodology Title')),
                ('our_methodology_description', models.TextField(verbose_name='Our Methodology Description')),
            ],
            options={
                'verbose_name': 'Interior Design Page',
                'verbose_name_plural': 'Interior Design Page',
            },
            bases=('others.seodata', models.Model),
        ),
        migrations.CreateModel(
            name='ArchitecturalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/architectural_service/', verbose_name='Image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectural_services', to='services.architectureservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Architectural Service',
                'verbose_name_plural': 'Architectural Services',
            },
        ),
        migrations.CreateModel(
            name='AdditionalExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_expertises', to='services.architectureservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Additional Expertise',
                'verbose_name_plural': 'Additional Expertises',
            },
        ),
        migrations.CreateModel(
            name='FitOutExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/fit_out_expertise/', verbose_name='Image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_out_expertises', to='services.fitoutservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Fit Out Expertise',
                'verbose_name_plural': 'Fit Out Expertises',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('slogan', models.CharField(max_length=50, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/expertise/', verbose_name='Image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='services.interiordesignservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Expertise',
                'verbose_name_plural': 'Expertises',
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/methodology/', verbose_name='Image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodologies', to='services.interiordesignservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Methodology',
                'verbose_name_plural': 'Methodologies',
            },
        ),
        migrations.CreateModel(
            name='MoreInformationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/more_information/', verbose_name='Image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_information_sections', to='services.fitoutservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'More Information Section',
                'verbose_name_plural': 'More Information Sections',
            },
        ),
        migrations.CreateModel(
            name='SpecializedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialized_services', to='services.fitoutservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Specialized Service',
                'verbose_name_plural': 'Specialized Services',
            },
        ),
        migrations.CreateModel(
            name='TransformationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/transformation_process/', verbose_name='Image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_processes', to='services.fitoutservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Transformation Process',
                'verbose_name_plural': 'Transformation Processes',
            },
        ),
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=256, verbose_name='Step')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_processes', to='services.architectureservice', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Work Process',
                'verbose_name_plural': 'Work Processes',
            },
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
