# Generated by Django 5.2 on 2025-05-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_architectureservice_fitoutservice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectureservice',
            options={'verbose_name': 'Architecture Page', 'verbose_name_plural': 'Architecture Page'},
        ),
        migrations.AlterModelOptions(
            name='fitoutservice',
            options={'verbose_name': 'Fit Out Page', 'verbose_name_plural': 'Fit Out Page'},
        ),
        migrations.AddField(
            model_name='fitoutservice',
            name='more_information_section_description',
            field=models.TextField(default=1, verbose_name='Additional Information Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitoutservice',
            name='more_information_section_title',
            field=models.TextField(default=1, verbose_name='Additional Information Title'),
            preserve_default=False,
        ),
    ]
