# Generated by Django 5.2 on 2025-04-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
            },
        ),
        migrations.CreateModel(
            name='FounderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='aboutUs/banners/', verbose_name='Founder image')),
            ],
            options={
                'verbose_name': 'Founder Section',
                'verbose_name_plural': 'Founder Section',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('image', models.ImageField(upload_to='aboutUs/banners/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Main Banner',
                'verbose_name_plural': 'Main Banner',
            },
        ),
        migrations.CreateModel(
            name='OptionalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Strategy Section',
                'verbose_name_plural': 'StrategySection',
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Best Services Section',
                'verbose_name_plural': 'Best Services Section',
            },
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutUs/banners/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Welcome Section',
                'verbose_name_plural': 'Welcome Section',
            },
        ),
        migrations.CreateModel(
            name='FounderBoldText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bold', models.TextField(verbose_name='Bold Text')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bold_text', to='aboutUs.foundersection', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Name')),
                ('percentage', models.IntegerField(verbose_name='Percentage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='aboutUs.optionalsection', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_banner', to='aboutUs.servicessection', verbose_name='Section')),
            ],
        ),
    ]
