# Generated by Django 5.2 on 2025-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Title'),
        ),
    ]
