# Generated by Django 5.2 on 2025-05-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_alter_mainbanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomesection',
            name='title',
            field=models.CharField(max_length=1056, verbose_name='Title'),
        ),
    ]
