# Generated by Django 5.2 on 2025-05-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0003_alter_welcomesection_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FounderBoldText',
        ),
    ]
