# Generated by Django 5.2 on 2025-05-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0004_delete_founderboldtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicessection',
            name='description',
            field=models.CharField(max_length=3056, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='title',
            field=models.CharField(max_length=1056, verbose_name='Title'),
        ),
    ]
