# Generated by Django 5.2 on 2025-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0005_alter_servicessection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesbanner',
            name='title',
            field=models.CharField(max_length=1052, verbose_name='Title'),
        ),
    ]
