# Generated by Django 5.2 on 2025-05-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0006_alter_servicesbanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalsection',
            name='title',
            field=models.CharField(max_length=1052, verbose_name='Title'),
        ),
    ]
