# Generated by Django 5.2 on 2025-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0007_alter_optionalsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalbanner',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
    ]
