# Generated by Django 5.2 on 2025-05-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0008_alter_optionalbanner_title'),
        ('others', '0005_alter_seodata_meta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('seodata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.seodata')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Main Banner image')),
                ('banner_description', models.TextField(verbose_name='Main Banner Description')),
                ('banner_slogan', models.CharField(max_length=256, verbose_name='Main Banner slogan')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Main Banner title')),
                ('welcome_section_title', models.CharField(max_length=256, verbose_name='Welcome Section Title')),
                ('welcome_section_description', models.TextField(verbose_name='Welcome Section Description')),
                ('welcome_section_stats', models.JSONField(default=list, help_text='{"value": "data", "label": "data"},', verbose_name='Stats')),
                ('founder_image', models.ImageField(upload_to='aboutUs/founder/', verbose_name='Founder Image')),
                ('founder_words', models.TextField(verbose_name='Founder Words')),
                ('our_team_section_description', models.TextField(verbose_name='Our Team Section Description')),
                ('our_essence_section_title', models.CharField(max_length=128, verbose_name='Our Essence Section Title')),
                ('our_essence_section_description', models.CharField(max_length=128, verbose_name='Our Essence Section Description')),
                ('services_section_title', models.TextField(verbose_name='Services Section Title')),
                ('services_section_description', models.TextField(verbose_name='Services Section Description')),
                ('interior_design_service_description', models.TextField(verbose_name='Interior Design Service Description')),
                ('interior_design_service_image', models.ImageField(upload_to='aboutUs/services/', verbose_name='Interior Design Service Image')),
                ('fit_out_service_description', models.TextField(verbose_name='Fit Out Service Description')),
                ('fit_out_service_image', models.ImageField(upload_to='aboutUs/services/', verbose_name='Fit Out Service Image')),
                ('architecture_service_description', models.TextField(verbose_name='Architecture Service Description')),
                ('architecture_service_image', models.ImageField(upload_to='aboutUs/services/', verbose_name='Architecture Service Image')),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
            bases=('others.seodata', models.Model),
        ),
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='aboutUs/essence/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Essence',
                'verbose_name_plural': 'Our Essences',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('position', models.CharField(max_length=256, verbose_name='Position')),
                ('image', models.ImageField(upload_to='aboutUs/team/', verbose_name='Team Member Image')),
                ('bio', models.TextField(verbose_name='Bio')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.DeleteModel(
            name='FAQSection',
        ),
        migrations.DeleteModel(
            name='FounderSection',
        ),
        migrations.DeleteModel(
            name='MainBanner',
        ),
        migrations.RemoveField(
            model_name='optionalbanner',
            name='section',
        ),
        migrations.RemoveField(
            model_name='servicesbanner',
            name='section',
        ),
        migrations.RemoveField(
            model_name='servicesbanner',
            name='services',
        ),
        migrations.DeleteModel(
            name='WelcomeSection',
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='our_essence',
            field=models.ManyToManyField(blank=True, to='aboutUs.essence', verbose_name='Our Essence'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='team_members',
            field=models.ManyToManyField(blank=True, to='aboutUs.teammember', verbose_name='Team Members'),
        ),
        migrations.DeleteModel(
            name='OptionalBanner',
        ),
        migrations.DeleteModel(
            name='OptionalSection',
        ),
        migrations.DeleteModel(
            name='ServicesSection',
        ),
        migrations.DeleteModel(
            name='ServicesBanner',
        ),
    ]
