# Generated by Django 5.2 on 2025-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0009_aboutuspage_essence_teammember_delete_faqsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage',
            name='welcome_section_description',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='welcome_section_title',
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='welcome_section',
            field=models.TextField(default=1, verbose_name='Welcome Section'),
            preserve_default=False,
        ),
    ]
