# Generated by Django 5.2 on 2025-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0010_remove_aboutuspage_welcome_section_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='our_essence_section_description',
            field=models.CharField(max_length=512, verbose_name='Our Essence Section Description'),
        ),
    ]
