# Generated by Django 5.2 on 2025-04-28 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInteriorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='home/about-interior/', verbose_name='Upload image')),
            ],
            options={
                'verbose_name': 'About Interior',
                'verbose_name_plural': 'About Interiors',
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='home/sections/', verbose_name='Upload image')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='BannerCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Text for the CTA button (e.g., 'Read More')", max_length=100)),
                ('url', models.CharField(help_text="URL the CTA button links to (e.g., '/about')", max_length=200)),
            ],
            options={
                'verbose_name': 'Main Banner CTA',
                'verbose_name_plural': 'Main Banner CTAs',
            },
        ),
        migrations.CreateModel(
            name='BeforeAfterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('before_image', models.ImageField(upload_to='home/before-after/', verbose_name='Before image')),
                ('after_image', models.ImageField(upload_to='home/after-before/', verbose_name='After image')),
            ],
            options={
                'verbose_name': 'Before After Section',
                'verbose_name_plural': 'Before After Sections',
            },
        ),
        migrations.CreateModel(
            name='FeaturedServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('image', models.ImageField(upload_to='home/services/', verbose_name='Upload image')),
            ],
            options={
                'verbose_name': 'Featured Services',
                'verbose_name_plural': 'Featured Services',
            },
        ),
        migrations.CreateModel(
            name='ReviewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(verbose_name='Stars')),
                ('review', models.TextField(verbose_name='Review')),
                ('image', models.ImageField(upload_to='home/reviews/', verbose_name='Client image')),
                ('client_fullname', models.CharField(max_length=512, verbose_name='Client fullname')),
                ('client_position', models.CharField(max_length=512, verbose_name='Client position')),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='AboutInteriorBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_interior_banner_set', to='homepage.aboutinteriorsection')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Banner name')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='home/sections/', verbose_name='Upload image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_banner_set', to='homepage.aboutsection')),
            ],
        ),
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], help_text='Type of slide content: image or video', max_length=10)),
                ('src', models.FileField(help_text='Upload image (jpg, jpeg, png) or video (mp4) file', upload_to='banner_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])])),
                ('title', models.CharField(help_text='Main title of the slide', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description text', null=True)),
                ('category', models.CharField(blank=True, help_text="Optional category (e.g., 'A TRENDY LUXURY')", max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text="Optional phone number (e.g., '+971 55 407 3275')", max_length=20, null=True)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('split', 'Split')], default='left', help_text='Content alignment: left, center, right, or split', max_length=10)),
                ('social_links', models.BooleanField(default=False, help_text='Show social media links on the slide')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the slide in the banner')),
                ('cta', models.ForeignKey(blank=True, help_text='Optional Call-to-Action for the slide', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.bannercta')),
            ],
            options={
                'verbose_name': 'Main Banner Slide',
                'verbose_name_plural': 'Main Banner Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('image', models.ImageField(upload_to='home/featured-projects/', verbose_name='Upload image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_set', to='projects.project')),
            ],
            options={
                'verbose_name': 'Featured Projects',
                'verbose_name_plural': 'Featured Projects',
            },
        ),
        migrations.CreateModel(
            name='FeaturedServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Service name')),
                ('description', models.TextField(verbose_name='Service description')),
                ('image', models.ImageField(upload_to='home/services/', verbose_name='Upload image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.service')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_banner_set', to='homepage.featuredservicessection')),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=True, help_text='Enable autoplay for the banner')),
                ('autoplay_speed', models.PositiveIntegerField(default=5000, help_text='Autoplay speed in milliseconds (e.g., 5000)')),
                ('show_arrows', models.BooleanField(default=True, help_text='Show navigation arrows')),
                ('show_dots', models.BooleanField(default=False, help_text='Show navigation dots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slides', models.ManyToManyField(help_text='Slides included in this banner', to='homepage.bannerslide')),
            ],
            options={
                'verbose_name': 'Main Banner',
                'verbose_name_plural': 'Main Banners',
            },
        ),
    ]
