# Generated by Django 5.2 on 2025-05-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('others', '0005_alter_seodata_meta_keywords'),
        ('projects', '0007_alter_projectspage_options_project_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('seodata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.seodata')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Main Banner image')),
                ('banner_description', models.TextField(verbose_name='Main Banner Description')),
                ('banner_slogan', models.CharField(max_length=256, verbose_name='Main Banner slogan')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Main Banner title')),
                ('banner_subtitle', models.CharField(max_length=256, verbose_name='Main Banner subtitle')),
                ('featured_projects', models.ManyToManyField(blank=True, to='projects.project', verbose_name='Featured Projects')),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
            bases=('others.seodata', models.Model),
        ),
        migrations.CreateModel(
            name='StrategySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='home/strategy/', verbose_name='Upload image')),
                ('cta_first_title', models.CharField(max_length=20, verbose_name='CTA 1 Title')),
                ('cta_first_description', models.TextField(verbose_name='CTA 1 Description')),
                ('cta_second_title', models.CharField(max_length=20, verbose_name='CTA 2 Title')),
                ('cta_second_description', models.TextField(verbose_name='CTA 2 Description')),
            ],
            options={
                'verbose_name': 'Strategy Section',
                'verbose_name_plural': 'Strategy Sections',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Hotel Lobby or etc', max_length=512, verbose_name='Category')),
                ('review', models.TextField(verbose_name='Review')),
                ('fullname', models.CharField(max_length=512, verbose_name='Fullname')),
                ('icon', models.ImageField(upload_to='home/testimonials/', verbose_name='Icon')),
                ('stars', models.IntegerField(verbose_name='Stars')),
                ('position', models.CharField(max_length=512, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.RemoveField(
            model_name='aboutinteriorbanner',
            name='section',
        ),
        migrations.RemoveField(
            model_name='aboutsectionbanner',
            name='section',
        ),
        migrations.RemoveField(
            model_name='bannerslide',
            name='cta',
        ),
        migrations.RemoveField(
            model_name='luxurybanner',
            name='slides',
        ),
        migrations.DeleteModel(
            name='BeforeAfterSection',
        ),
        migrations.RemoveField(
            model_name='featuredprojectssection',
            name='project',
        ),
        migrations.RemoveField(
            model_name='featuredservicesbanner',
            name='section',
        ),
        migrations.RemoveField(
            model_name='featuredservicesbanner',
            name='service',
        ),
        migrations.DeleteModel(
            name='ReviewsSection',
        ),
        migrations.AddField(
            model_name='homepage',
            name='strategy_section',
            field=models.ManyToManyField(blank=True, to='homepage.strategysection', verbose_name='Strategy section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=models.ManyToManyField(blank=True, to='homepage.testimonial', verbose_name='Testimonials'),
        ),
        migrations.DeleteModel(
            name='AboutInteriorBanner',
        ),
        migrations.DeleteModel(
            name='AboutInteriorSection',
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='AboutSectionBanner',
        ),
        migrations.DeleteModel(
            name='BannerCTA',
        ),
        migrations.DeleteModel(
            name='BannerSlide',
        ),
        migrations.DeleteModel(
            name='LuxuryBanner',
        ),
        migrations.DeleteModel(
            name='FeaturedProjectsSection',
        ),
        migrations.DeleteModel(
            name='FeaturedServicesSection',
        ),
        migrations.DeleteModel(
            name='FeaturedServicesBanner',
        ),
    ]
