# Generated by Django 5.2 on 2025-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepage_strategysection_testimonial_and_more'),
        ('projects', '0007_alter_projectspage_options_project_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/testimonials/', verbose_name='Background Image of card'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_projects',
            field=models.ManyToManyField(blank=True, help_text='Select no more than 6 projects and -> ', to='projects.project', verbose_name='Featured Projects'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='strategy_section',
            field=models.ManyToManyField(blank=True, help_text='Select no more than 4 strategy section and -> ', to='homepage.strategysection', verbose_name='Strategy section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials',
            field=models.ManyToManyField(blank=True, help_text='Select no more than 4 testimonials and -> ', to='homepage.testimonial', verbose_name='Testimonials'),
        ),
    ]
