# Generated by Django 5.2 on 2025-05-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_testimonial_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='background_image',
            field=models.ImageField(default=1, upload_to='home/testimonials/', verbose_name='Background Image of card'),
            preserve_default=False,
        ),
    ]
