# Generated by Django 5.2 on 2025-05-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_testimonial_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategysection',
            name='cta_first_description',
            field=models.CharField(max_length=100, verbose_name='CTA 1 Description'),
        ),
        migrations.AlterField(
            model_name='strategysection',
            name='cta_second_description',
            field=models.CharField(max_length=100, verbose_name='CTA 2 Description'),
        ),
    ]
