# Generated by Django 5.2 on 2025-05-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_strategysection_cta_first_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategysection',
            name='cta_first_description',
        ),
        migrations.RemoveField(
            model_name='strategysection',
            name='cta_first_title',
        ),
        migrations.RemoveField(
            model_name='strategysection',
            name='cta_second_description',
        ),
        migrations.RemoveField(
            model_name='strategysection',
            name='cta_second_title',
        ),
        migrations.AddField(
            model_name='strategysection',
            name='stats',
            field=models.JSONField(default=list, help_text='{value: "data", label: "data"},', verbose_name='Stats'),
        ),
    ]
