# Generated by Django 5.2 on 2025-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_strategysection_cta_first_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_projects_description',
            field=models.TextField(default=1, verbose_name='Featured Projects section description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='strategy_section_description',
            field=models.TextField(default=1, verbose_name='Strategy section description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_description',
            field=models.TextField(default=1, verbose_name='Testimonials section description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategysection',
            name='stats',
            field=models.JSONField(default=list, help_text='{"value": "data", "label": "data"},', verbose_name='Stats'),
        ),
    ]
