# Generated by Django 5.2 on 2025-05-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_homepage_featured_projects_description_and_more'),
        ('projects', '0007_alter_projectspage_options_project_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_projects',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_project_normal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homepages_as_featured_normal', to='projects.project', verbose_name='Featured Project Normal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_project_normal_second',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homepages_as_featured_normal_second', to='projects.project', verbose_name='Featured Project Normal Second'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_project_normal_third',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homepages_as_featured_normal_third', to='projects.project', verbose_name='Featured Project Normal Third'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_project_tall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homepages_as_featured_tall', to='projects.project', verbose_name='Featured Project Tall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_project_wide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homepages_as_featured_wide', to='projects.project', verbose_name='Featured Project Wide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_project_wide_second',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homepages_as_featured_wide_second', to='projects.project', verbose_name='Featured Project Wide Second'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='strategy_section',
            field=models.ManyToManyField(blank=True, help_text='Select no more than 4 strategy section and -> ', related_name='homepages', to='homepage.strategysection', verbose_name='Strategy section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials',
            field=models.ManyToManyField(blank=True, help_text='Select no more than 4 testimonials and -> ', related_name='homepages', to='homepage.testimonial', verbose_name='Testimonials'),
        ),
    ]
