# Generated by Django 5.2 on 2025-04-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('projects', 'Projects'), ('contact', 'Contact Us')], default='home', max_length=100, unique=True, verbose_name='Страница')),
                ('meta_title', models.CharField(max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(max_length=1052, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (через запятую)')),
                ('og_title', models.CharField(blank=True, max_length=95, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=300, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='OG Image')),
                ('og_url', models.URLField(blank=True, verbose_name='OG URL')),
                ('structured_data', models.TextField(blank=True, help_text='\n        <b>Примеры JSON-LD для каждой страницы:</b><br><br>\n        <b>Главная страница (home):</b><br>\n        <pre>{\n          "@context": "https://schema.org",\n          "@type": "Organization",\n          "name": "Название вашей компании",\n          "url": "https://example.com",\n          "logo": "https://example.com/logo.png"\n        }</pre>\n        <b>О нас (about):</b><br>\n        <pre>{\n          "@context": "https://schema.org",\n          "@type": "Organization",\n          "name": "Название вашей компании",\n          "url": "https://example.com/about",\n          "description": "Краткое описание вашей компании."\n        }</pre>\n        <b>Проекты (projects):</b><br>\n        <pre>{\n          "@context": "https://schema.org",\n          "@type": "CollectionPage",\n          "name": "Наши проекты",\n        }</pre>\n        <b>Контакты (contact):</b><br>\n        <pre>{\n          "@context": "https://schema.org",\n          "@type": "ContactPage",\n          "name": "Свяжитесь с нами",\n          "url": "https://example.com/contact"\n        }</pre>\n        ', verbose_name='Структурированные данные (JSON-LD)')),
            ],
            options={
                'verbose_name': 'SEO данные',
                'verbose_name_plural': 'SEO данные',
            },
        ),
    ]
