# Generated by Django 5.2 on 2025-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seodata',
            name='structured_data',
        ),
        migrations.AlterField(
            model_name='seodata',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('projects', 'Projects'), ('contacts', 'Contact Us')], default='home', max_length=100, unique=True, verbose_name='Страница'),
        ),
    ]
