# Generated by Django 5.2 on 2025-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_remove_seodata_structured_data_alter_seodata_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seodata',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About Us'), ('projects', 'Projects'), ('contacts', 'Contact Us')], default='home', max_length=100, unique=True, verbose_name='Select page'),
        ),
    ]
