# Generated by Django 5.2 on 2025-05-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_alter_seodata_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seodata',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seodata',
            name='og_url',
        ),
        migrations.RemoveField(
            model_name='seodata',
            name='page',
        ),
        migrations.AddField(
            model_name='feedback',
            name='fullname',
            field=models.CharField(default=1, max_length=100, verbose_name='Fullname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.CharField(default=1, max_length=100, verbose_name='Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='meta_description',
            field=models.CharField(max_length=158, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=158, verbose_name='Meta Keywords (через запятую)'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='meta_title',
            field=models.CharField(max_length=55, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='og_description',
            field=models.CharField(blank=True, max_length=158, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='og_title',
            field=models.CharField(blank=True, max_length=55, verbose_name='OG Title'),
        ),
    ]
