# Generated by Django 5.2 on 2025-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_alter_seodata_options_remove_feedback_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seodata',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=158, verbose_name='Meta Keywords - separated by commas'),
        ),
    ]
