# Generated by Django 5.2 on 2025-05-22 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_alter_seodata_meta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('seodata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='others.seodata')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Main Banner image')),
                ('banner_description', models.TextField(verbose_name='Main Banner Description')),
                ('banner_slogan', models.CharField(max_length=256, verbose_name='Main Banner slogan')),
                ('banner_title', models.CharField(max_length=256, verbose_name='Main Banner title')),
                ('location_title', models.CharField(max_length=256, verbose_name='Location Title')),
                ('location_description', models.TextField(verbose_name='Location Description')),
                ('call_title', models.CharField(max_length=256, verbose_name='Call Title')),
                ('call_number', models.CharField(max_length=256, verbose_name='Call Number')),
                ('email_title', models.CharField(max_length=256, verbose_name='Email Title')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('working_hours_title', models.CharField(max_length=256, verbose_name='Working Hours Title')),
                ('working_hours_description', models.TextField(verbose_name='Working Hours Description')),
                ('our_location_description', models.TextField(verbose_name='Our Location Description')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
            bases=('others.seodata', models.Model),
        ),
    ]
