# Generated by Django 5.2 on 2025-05-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Dont Need !'),
        ),
    ]
